version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_goto
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: goto
      MONGO_INITDB_ROOT_PASSWORD: goto
      MONGO_INITDB_DATABASE: goto
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
