services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_goto
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
      MONGO_INITDB_DATABASE: game
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
