server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: game
  data:
    mongodb:
      uri: mongodb://localhost:27017/game
      database: game

api:
  version: v1
  base-path: /api/v1