server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: game

  datasource:
    url: jdbc:postgresql://localhost:5432/game
    username: goto
    password: goto
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 3000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Ensures schema exists but doesn't modify it
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

api:
  version: v1
  base-path: /api/v1